generic: &generic
  #database: don't specify one here!  Set it below.
  adapter: mysql
  host: localhost
  username: root
  password: password
  socket: /tmp/mysql.sock
  encoding: utf8

development:
  database: cf-rails-dev
  <<: *generic

test:
  database: cf-rails-test
  <<: *generic

production:
  database: cf-rails-production
  <<: *generic

