#!/usr/bin/env bash

# wrapper script to run CloudFoundry gem under ruby-2.0.0, it doesn't run under Ruby 1.8.7, which is project default
# Install with: rvm ruby-2.0.0 do gem install cf

rvm ruby-2.0.0 do cf $*
